title: Nishit Patel
email: nishitlimbani130@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nishitpatel.tech" # the base hostname & protocol for your site, e.g. http://example.com
disqus: "blog-iiu4zzvb3v"
twitter_username: nishit130
github_username:  nis130

google_analytics: "UA-150355837-1"

# Build settings
# theme: alembic-jekyll-theme
# remote_theme: daviddarnes/alembic
plugins:
  - jekyll-feed
  # - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


encoding: utf-8 # Make sure the encoding is right
lang: en-IN # Set the site language
title: "Nishit Patel" # Site name or title, also used in jekyll-seo-tag
description: "Portfolio webstie of Nishit Patel" # Site description and default description, also used in jekyll-seo-tag
twitter_url: "https://twitter.com/nishit130"
linkedin_url: "https://www.linkedin.com/in/nishit-patel-45a8b0136/"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml

navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: Blog Post's
    feature_image: "https://picsum.photos/1300/400?image=989"


sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
